Update README.md
rdfjs/N3.js pull request #287
Opened 2022-04-15 23:36 UTC by jeswr

References and aligns with the `DatasetCore` api per https://github.com/rdfjs/N3.js/issues/286#issuecomment-1100438631

2022-04-15 23:37 UTC, jeswr commented
Pinging @rubensworks since you did a lot of work on that spec.

2022-04-18 14:26 UTC, TallTed requested changes
Backtick codefences are insufficient division for many screen readers and other accommodations for those with vision issues. Em-dash or similar dividers are recommended for all such "`term` — definition or description" line items.

2022-04-18 14:26 UTC, TallTed commented on README.md
> + - `size` A non-negative integer that specifies the number of quads in the set.
```suggestion
 - `size` — A non-negative integer that specifies the number of quads in the set.
```

2022-04-18 14:26 UTC, TallTed commented on README.md
> + - `[Symbol.iterator]` Implements the iterator protocol to allow iteration over all `quads` in the dataset as in the example above.
```suggestion
 - `add` — Adds the specified quad to the dataset. Existing quads, as defined in `Quad.equals`, will be ignored.
 - `delete` — Removes the specified quad from the dataset.
 - `has` — Determines whether a dataset includes a certain quad.
 - `match` — Returns a new dataset that is comprised of all quads in the current instance matching the given arguments.
 - `[Symbol.iterator]` — Implements the iterator protocol to allow iteration over all `quads` in the dataset as in the example above.
```

2022-05-10 08:22 UTC, jeswr commented
Pinging @RubenVerborgh for review

2022-05-10 12:06 UTC, merged