Update README.md
rdfjs/N3.js pull request #354
Opened 2023-05-30 10:40 UTC by mimfa

There I added some comments

2023-05-30 12:32 UTC, jeswr requested changes

2023-05-30 12:32 UTC, jeswr commented on README.md
> +const writer = new N3.Writer({ prefixes: { c: 'http://example.org/cartoons#' } }); // Create a writer with a special context as Graph
```suggestion
const writer = new N3.Writer({ prefixes: { c: 'http://example.org/cartoons#' } }); // Create a writer which uses `c` as a prefix for the namespace http://example.org/cartoons#
```

2023-06-01 15:49 UTC, TallTed commented on README.md
> +const writer = new N3.Writer({ prefixes: { c: 'http://example.org/cartoons#' } }); // Create a writer with a special context as Graph
```suggestion
const writer = new N3.Writer({ prefixes: { c: 'http://example.org/cartoons#' } }); // Create a writer which uses `c` as a prefix for the namespace `http://example.org/cartoons#`
```

2023-06-04 01:23 UTC, jeswr approved these changes

2023-06-04 01:23 UTC, merged