fix/indexing quoted triples
rdfjs/N3.js pull request #369
Opened 2023-10-20 15:04 UTC by jeswr

- fix: support deeply nested triples in termFromId and termToId
- chore: extend dataset tests for deeply nested triples
- perf: index terms of quoted triples

2023-10-20 17:06 UTC, TallTed requested changes

2023-10-20 17:06 UTC, TallTed commented on test/N3Store-test.js
> +  // at such a time
The portion following the semicolon needs rewriting. At present, it is indecipherable.

2023-10-20 19:01 UTC, jeswr commented on test/N3Store-test.js
> +  // at such a time
```suggestion
```

2023-10-27 13:09 UTC, RubenVerborgh approved these changes
Okay that's quite cool 😎 Looks good to me!

2023-10-27 13:58 UTC, merged